theme: jekyll-theme-minimal
logo: /images/person.png
title: Welcome to LinZhao's homepage
description: 
  - Lin Zhao  
  
  - Feel free to bookmark this to keep an eye on my project updates!

autor: Lin Zhao


